name: Matthew Bowlin
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Matthew Bowlin - Photo Artist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefdf8'
    - '#c8c1a7'
    - '#7c5e00'
    - '#aa850f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
