name: Matthew Bowlin
favicon: null
layout_spectrum: 0.3709192629903555
typography_spectrum: 0.5589604512788355
title: 'I take pictures. Send me an email. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.15013607474975288
  lightness: 0.01978415041230619
  saturation: 0.5916045426856726
  rhythmicContrast: 0.5265887272544205
purpose: []
